#!/usr/bin/env bash
# Installs and configures HAproxy with version 1.5 or greater
#+ in order to send trafic to web-01 and web-02
apt-get -y install haproxy

# edit config file
server_config=\
"
frontend we0102
        bind *:80
        mode http
        default_backend kenmind-alx_back
backend web_backend
        balance roundrobin
        server 1687-web-01 44.192.38.157:80 check
        server 1687-web-02 44.201.106.82:80 check
"
 echo "$server_config" >> /etc/haproxy/haproxy.cfg

 echo "ENABLED=1" >> /etc/default/haproxy

 sudo service haproxy restart
