#!/usr/bin/env bash
# displays numbers from 1 to 100
# displays FizzBuzz when the number is a multiple of 3 and 5
# displays Fizz when the number is a multiple of 3
# diplays Buzz when the number is a multple of 5

for i in {1..100}
do
	let z=$i%3 
	let p=$i%5
	if [[ $z -eq 0 && $p -eq 0 ]]
	then
		echo FizzBuzz
	elif [ $p -eq 0 ]
	then
		echo Buzz
	elif [ $z -eq 0 ]
	then
		echo Fizz
	else
		echo $i
	fi
done
