#!/usr/bin/env bash
# dispalys the content of the current directory
# in a list format where
# only the part of the name after 1st dash is displayed

z=$(ls | cut -d '-' -f2 )
for i in $z
do
	echo "$i"
done
