#!/usr/bin/env bash
# dispalys the content of the current directory
# in a list format where
# only the part of the name after 1st dash is displayed

current_dir=$(PWD)
z=$(ls $current_dir | cut -d '-' -f2 )
for i in $z
do
	echo $i
done
