#!/usr/bin/env bash
# displays the content of the current directory
# in a list format where
# only the part of the name after 1st dash is displayed

z=$(ls)
for i in $z
do
	echo "$i" | cut -d '-' -f2
done
